### ISSUE TITLE
Add behind the scenes "refresh" method for when to update our local cache from online

### ISSUE THREAD

**Issue by falon3** [CMPUT301F15T15/Team15Alpha#106]
So Noah and I chatted about this happening where we have it so we search for things from our local cache only and just update it with everything that is online every so often (on start up and when refreshed)... rather than doing search inquiries to elastic every time because that is slow. I suppose this ties in with what Noah is doing with Search issue, but there needs to be a button made for refresh anyways.... maybe Elyse can do this up?

**Comment by FancifulEight** [comment]
Maybe it should be an automatic update?
I think that's what we were talking about before

**Comment by falon3** [comment]
but how often then? Just thought it would be automatic when turning on again, but have it only update info thereafter during the same session on refresh? How will it automatically update every other users account when one user adds a skill or something then?... I mean how would it know? But maybe refresh me on what you say we decided the other day was best then, all ears: how so automatic?

**Comment by falon3** [comment]
Okay ya we are just gonna have it so every time a new activity happens our "refresh" method is called that updates everything... but first we will check if there is internet connection. If that's fine with everyone.... seemed to be agreed upon between Cole, Noah and I

**Comment by nwoeanhinnogaehr** [comment]
I think this got fixed at some point
