### ISSUE TITLE
Either figure out how to Populate elastic via terminal or from our Java code

### ISSUE THREAD

**Issue by falon3** [CMPUT301F15T15/Team15Alpha#15]
Tried to do this via the terminal... the documentation is horrible for doing anything complicated (a nested list)

Skill needs: ID, Descriptions, Visibility, Owner, Picture?, Category

Store details of profiles (see android studio class details to see what is needed)

We need to keep a list of Skills, Users, Trades, (anything else I can't remember) in our database so how to organize this is key

**Comment by nwoeanhinnogaehr** [comment]
Woah how did you manage to assign and unassign so many people so quickly?? :)

**Comment by falon3** [comment]
hahahah shit, did everyone get notifications? haha it was cuz I wanted to put more than one person on this but couldn't figure out how... it kept overwriting and I'm tired so it was a cycle for a little while haha. til i gave up. But we all now know it;s important haha

**Comment by nwoeanhinnogaehr** [comment]
#38 #39 #40

**Comment by FancifulEight** [comment]
This is presumably complete.
Good Job Noah!
