### ISSUE TITLE
Discuss and credit our use of Esspresso

### ISSUE THREAD

**Issue by falon3** [CMPUT301F15T15/Team15Alpha#159]
Uhhh first read over our specs and figure out what all has to be done for this, cuz I can't remember right now but it does need to be mentioned somewhere

**Comment by FancifulEight** [comment]
It needs to referred in the README, I think

**Comment by falon3** [comment]
"Reuse Statement:
Document instances of software reuse. Give proper credit to the original developers. Obtain approval for the use of third-party libraries as appropriate. Enter this information in your team wiki." 
This would be use of espresso then right? What else did we use??

**Comment by falon3** [comment]
I did this in README .... should be good enough I think
