### ISSUE TITLE
When edit/delete/add something offline it doesn't persist once when go back online

### ISSUE THREAD

**Issue by falon3** [CMPUT301F15T15/Team15Alpha#162]
Local changes that happen offline only persist if we remain offline..... weird bug but draining time into debugging is not a priority really until everything else is implemented.

**Comment by FancifulEight** [comment]
Urgent enough

**Comment by FancifulEight** [comment]
Isn't this fixed though?

**Comment by falon3** [comment]
needs to be tested again I guess, I'll do this if I have time at work tonight

**Comment by falon3** [comment]
fixed!
