### ISSUE TITLE
Reduce use of "Magic" numbers and strings

### ISSUE THREAD

**Issue by nwoeanhinnogaehr** [CMPUT301F15T15/Team15Alpha#167]
There are all throughout the codebase, things like the strings we pass as extra names, the strings representing types on elastic, the screenType on SearchScreenActivity... Ideally these would be factored out into constants so they can be changed if needed, without having to change every place they are used.

https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants

**Comment by FancifulEight** [comment]
This is a coding choice, not a necessity.
But yes, when it's not obvious, you should give it a name.

**Comment by FancifulEight** [comment]
I am curious though, where do you see "Magic" numbers and strings in our code?

(I have some in the category searching, but they're pretty easy to understand)

**Comment by nwoeanhinnogaehr** [comment]
I just wanted to bring this up because I got my assignment 1 back and hindle commented on it...

Stuff like when we do putExtra("All_search", 1) should be putExtra(PARAM_SEARCH_TYPE, SEARCH_TYPE_USER)

**Comment by falon3** [comment]
good enough
