### ISSUE TITLE
Try to avoid static methods, except for if you are following the singleton pattern

### ISSUE THREAD

**Issue by nwoeanhinnogaehr** [CMPUT301F15T15/Team15Alpha#168]
Yes I know this probably isn't worth fixing, but we can avoid making it worse. https://en.wikipedia.org/wiki/Singleton_pattern

**Comment by FancifulEight** [comment]
You may have to give a crash course on this to Cole

**Comment by FancifulEight** [comment]
We also might need a team meeting discussion
