### ISSUE TITLE
Rating system

### ISSUE THREAD

**Issue by falon3** [CMPUT301F15T15/Team15Alpha#179]
entire thing needs to be done..... "Top Traders" see use case

**Comment by FancifulEight** [comment]
I understand what the problem is! I set NumStars, which does not mean the rating, but the max possible rating! That's why Noah was having disappearing stars!

**Comment by FancifulEight** [comment]
I'm writing this down here, because I just did the Trades thing and should go to bed

**Comment by FancifulEight** [comment]
This issue should be closed once I fix that

**Comment by FancifulEight** [comment]
Apparently We DON'T NEED THIS
