### ISSUE TITLE
photo thumbnail stuff for skills

### ISSUE THREAD

**Issue by falon3** [CMPUT301F15T15/Team15Alpha#180]
mostly done... needs few extras and fancier icon

**Comment by FancifulEight** [comment]
How so?

**Comment by FancifulEight** [comment]
The only thing I can think of is either having user avatars(which are unnecessary) or cropping the bitmap so the images appear as circles(would look nicer, but again, unnecessary)

**Comment by falon3** [comment]
I dunno i asked if this was done and the answer was no so I left it open
