### ISSUE TITLE
FriendsList is missing important features.

### ISSUE THREAD

**Issue by nwoeanhinnogaehr** [CMPUT301F15T15/Team15Alpha#29]
There's no way to deny a friend request.

There's no way to unblock a user.

These methods will need to be added to both the UML and the class.

**Comment by nwoeanhinnogaehr** [comment]
4f09deef7d59676635b47ace4360a28649ba2134 fixed the code, UML still needs to be updated.

**Comment by falon3** [comment]
I'll update the UML for this tomorrow

**Comment by falon3** [comment]
just gotta put new UML up
