### ISSUE TITLE
change add skill use case

### ISSUE THREAD

**Issue by falon3** [CMPUT301F15T15/Team15Alpha#293]
edit it so it reflects the flow of testAddSkillz in Espressotest file that makes a brand new skill

**Comment by falon3** [comment]
also change remove skill flow to remove the skill from viewing it in the user inventory NOT the list of all skills

**Comment by falon3** [comment]
modify skill details use case also needs flow updated to reflect our actual buttons

**Comment by evhill** [comment]
Went through all the use cases and fixed them to be accurate of our app. Potentially I missed something as it was at 4:30 am
