### ISSUE TITLE
update UML to cover all basic functionality before handing in

### ISSUE THREAD

**Issue by nwoeanhinnogaehr** [CMPUT301F15T15/Team15Alpha#5]

**Comment by FancifulEight** [comment]
May be done, depends on the complexity we wish to show

**Comment by falon3** [comment]
specially should at least add our controller stuff

**Comment by falon3** [comment]
Specs say:
"including detail on key attributes and methods. Include notes on the use of design patterns among the classes."
" The code base must match the UML. "

**Comment by falon3** [comment]
is this finished and final then Cole?
